### ISSUE TITLE
Max Evaluations in Iterations not working as expected

### ISSUE THREAD

**Issue by kevindanray** [jeffgortmaker/pyblp#95]
I have used the following code for my iteration routine:
`pyblp.Iteration('squarem', {'max_evaluations': 50000})`
but when running the the problem.solve method (bfgs algorithm) I see things like the following:

At least one error was encountered. As long as the optimization routine does not get stuck at values of theta that give rise to errors, this is not necessarily a problem. If the errors persist or seem to be impacting the optimization results, consider setting an error punishment or following any of the other suggestions below:
The fixed point computation of delta failed to converge. This problem can sometimes be mitigated by increasing the maximum number of fixed point iterations, increasing the fixed point tolerance, choosing more reasonable initial parameter values, setting more conservative parameter or share bounds, or using different iteration or optimization configurations.
Encountered a numerical error when computing delta. This problem is often due to prior problems, overflow, or nonpositive shares, and can sometimes be mitigated by choosing smaller initial parameter values, setting more conservative bounds on parameters or shares, rescaling data, removing outliers, changing the floating point precision, or using different optimization, iteration, or integration configurations. Errors encountered: divide by zero.

` 1         5            11         4931583     14795679       0     +6.29E+05               +1.18E+05`

where 4,931,583 is the "Fixed Point Iterations" and 14,795,679 is the "Contraction evaluations".

After spending hours upon hours performing these millions of evaluations, it moves on and performs fine, but there is a lot of time lost when it seems like it should stop at 50,000 as the iteration configuration is written.

**Comment by jeffgortmaker** [comment]
Ah I think the confusion is coming from the fact that the contraction is solved market-by-market. So if you have 3 markets and each takes 50,000 iterations, "Contraction Evaluations" will show 150,000.

What's likely happening is the iteration routine is encountering some trouble in a couple markets where it uses up the full 50,000, and not having trouble in other markets, so you get a number of contraction evaluations that isn't divisible by 50,000.

By the way, there's a decent chance the issue you're encountering is the same as #85 and #89. If so, I've pushed a fix to the dev version of the code (I should really include this in a new stable version of the package when I find the time ...), so you could clone this repo and use the dev version. Or you could use a different iteration routine than squarem (e.g., lm or simple) which doesn't have the same issue. But if it's some other problem, happy to help debug that too.

**Comment by kevindanray** [comment]
I will see how it behaves with the new version, but it is helpful to know that the maximum iterations is per market (that much wasn't clear from the documentation). At the moment it still seems to be bogging down at some points due to non-convergence of the inner loop. Provided that I can reduce the number of iterations and it doesn't get stuck doing that, I don't see the need for further debugging.

Might the "lm" routine be faster in this scenario?

**Comment by jeffgortmaker** [comment]
So the issue I linked above is an actual bug with my implementation of SQUAREM that led to non-convergence because of a numerical error. Using lm with the old code would be "faster" in the sense that it shouldn't have the same bug, so presumably it should do better in terms of convergence. 

More generally, we've found lm to be the fastest Jacobian-based method. In some of the cases we looked at it outperformed SQUAREM, which is the fastest non-Jacobian method we know of. But this will vary case-by-case (depending on e.g. the  Lipschitz constant of the contraction), so it's good to try out different ones if you're concerned about speed.

**Comment by kevindanray** [comment]
So even with v 0.12.0 SQAREM is still getting stuck at the exact same step. But this time I set the max to 10,000. This time it doesn't have the "divide by zero" part of the error, though.

`
 1         5            11         1064124      3193025       0     +6.29E+05               +1.18E+05`

**Comment by jeffgortmaker** [comment]
So to be clear, you're using the dev code by cloning the repo? Just checking because the most recent stable version is also tagged with 0.12.0.

Without any more info it's hard to tell why SQUAREM isn't converging. Maybe trying different iteration routines would help,. You could also set up a problem with only a couple of markets, one in which the routine converges and one in which it doesn't (this will require some trial and error), to get a sense of what about a market makes the routine not converge.

**Comment by jeffgortmaker** [comment]
I'm going to close this issue for now since it seems like you may have gotten past the issue? But please re-open if not, or if you have other questions.
